wordpress:
  image:
    repository: wordpress
    tag: latest
  name: my-wordpress
  externalDatabase:
    host: mysql-wordpress
    user: wordpress
    password: example
    database: wordpress

mysql:
  image:
    repository: mysql
    tag: latest
  name: mysql-wordpress
  rootPassword: example
  wordpressDatabase: wordpress
  wordpressUser: wordpress
  wordpressPassword: example

phpmyadmin:
  image:
    repository: phpmyadmin/phpmyadmin
    tag: latest
  name: phpmyadmin
  ingress:
    enabled: true
    host: koosha-orazizade-nl-rg2.maxtld

ingress:
  enabled: true
  host: koosha-orazizade-nl-rg2.maxtld

